### ISSUE TITLE
login and @login_required-type functionality

### ISSUE THREAD

**Issue by russellromney** [ned2/slapdash#10]
Slapdash is great! Thanks for making this, and for all your other work on Dash.

I'm pretty new to Flask but I've figured out how to implement login, registering, etc. in basic Dash+Flask using flask-login. But in Slapdash it's not super clear to me how I can implement my own functions for login, logout, etc. and use extension decorators - for example, to protect certain pages with @login_required but leave others open (e.g. a public blog for a private product).

How would I go about doing that? Explanations and links appreciated equally.

**Comment by dustyny** [comment]
I would like to generalize this question to

**### "How to manage security?"** 

Dash auth
Flask auth
AWS Cognito
Auth0
Stormpath
...
...
...

**Comment by russellromney** [comment]
I had used [dash_google_auth](https://github.com/lucaschapin/dash-google-auth) before and tried it out in this case. This is similar to the example on the dash-google-auth package.

```
## /src/slapdash/app.py
# ...
from werkzeug.contrib.fixers import ProxyFix
from dash_google_auth import GoogleOAuth 
from .google_auth_ids import * ## client ID & secret as variables in src/slapdash/google_auth_ids
from .emails import authorized_emails  ## list of emails in src/slapdash/emails
import os

# The Flask instance
server = create_app()

# The Dash instance
app = create_dash(server)

# configure app & google auth stuff
server.wsgi_app = ProxyFix(server.wsgi_app)
server.config["GOOGLE_OAUTH_CLIENT_ID"] = google_oath_client_id
server.config["GOOGLE_OAUTH_CLIENT_SECRET"] = google_oath_client_secret
server.secret_key = os.environ.get("secret_key", "super_sekret")

auth = GoogleOAuth(
    app,
    authorized_emails,
)
# ...
```

```
## /src/slapdash/run_flask.py
# ...
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'     # to run locally
# ...
```

This works for the most basic part - login - but doesn't work for creating your own database of users, or for requiring login for certain parts of your app and freeing others. 

The Slapdash router is handy but doesn't allow custom route functions, so to allow them you just need to deconstruct the router into individual functions. Will try that.

**Comment by russellromney** [comment]
Thanks for answering, at least. As I've worked with it more I've seen the problem being me just not knowing how to use flask-login with Dash, bc even if I use the `@login_required` decorator with an `app.route` function that returns the given layout, it shows it when you type the URL rather than clicking on a link that redirects to the URL where the Dash app is. So, yeah.
