### ISSUE TITLE
readme - sections `run-slapdash-dev` and `run-slapdash-prod` are innacurate

### ISSUE THREAD

**Issue by johnmathews** [ned2/slapdash#20]
great project.

Getting set up was tricky, partly because the readme is incorrect. 

> Installing this package into your virtualenv will result into the run-slapdash-dev executable being installed into the same virtualenv. 

the script is called `run-<project-name>-dev` . the same for prod. 

Also, maybe its because I'm running pyenv or virtualenvwrapper, but the virtualenv exists in `~/.virtualenvs/<venv-name>` and therefore running the command takes extra steps -  either type the path to the venv, or add my venv to `PATH`.

**Comment by ned2** [comment]
Thanks for raising this, good spot. Now fixed.

I'm managing virtualenv's with pyenv and have the scripts winding up in my path fine, so not sure what's going on it your setup.

**Comment by johnmathews** [comment]
I set up another slapdash project on a different machine and didn't have the $PATH issues, so I guess it can be ignored.

do you have any plans to continue developing slapdash?

imo, it would be useful to have the option to choose between structuring a project as it currently is (its own package and running it with shell commands), or a more vanilla `python app.py` approach that is more flexible for deploying into existing environments. I deployed slapdash into a large co's pre-configured (inflexible) environment and had to refactor it fairly heavily. I'd be interested to contribute depending on what your priorities are.

**Comment by ned2** [comment]
Good to hear that the path were resolved!

Yep, I will be continuing to work on Slapdash.

I'd be curious to know exactly what your friction point regarding deployment was. I have tried to design Slapdash to be friendly towards best practice for deployment of Python WSGI apps. This means running with a WSGI server. The following is pretty straightforward:

    gunicorn --bind 0.0.0.0:8000 slapdash.wsgi

I think it is also possible to run this way without installing the package into your virtual environment. If there are specific difficulties that this type of deployment doesn't work for you, would you be able to create a new issue describing them?
