### ISSUE TITLE
bad key searched in kwargs

### ISSUE THREAD

**Issue by moas** [ned2/slapdash#28]
https://github.com/ned2/slapdash/blob/1a79a4e64e17bb6f9fbf4666487f9b6c88c2f13d/%7B%7Bcookiecutter.project_slug%7D%7D/src/%7B%7Bcookiecutter.project_slug%7D%7D/utils.py#L26

**Comment by ned2** [comment]
Ah yes, oops. Good catch thanks.

Fixed with #d4ae2f4dfd87459de2454ce5b4b4889b37b8ddbb
