### ISSUE TITLE
Use Waitress with Slapdash?

### ISSUE THREAD

**Issue by Quaternion66** [ned2/slapdash#30]
Slapdash is great for developing my Dash app.
Unfortunately, I am too much of a newbie to get slapdash working with waitress, on Windows 10 and Mac OSX. 
I tried to point to the wsgi.py file.
I suppose I have to import waitress there, but I don’t know how.
Can you help me with that?

Best regards, Rob

**Comment by ned2** [comment]
Unfortunately I can't help here as I've never used Waitress before
