### ISSUE TITLE
pip install error  "no such option: -s"

### ISSUE THREAD

**Issue by brylie** [ned2/slapdash#4]
The README says to install slapdash with the command `pip install -s .`. However, that command gives an error:

> no such option: -s

# Environment
pip version: 18.1

**Comment by brylie** [comment]
Things seem to work when I run `pip install .` without the `-s` flag. 

As an aside, is it possible to use this project without running `pip install`? E.g. just use the file structure without installing the `slapdash` package?

**Comment by ned2** [comment]
oops, that was my bad. Should be `pip install -e .` Just pushed a fix to the readme. That flag installs slapdash in editable mode, so that any changes to the code in the cloned repository are reflected in the installed app.

**Comment by brylie** [comment]
Would it be possible to use this architecture without the need for the slapdash package? I would gladly follow a tutorial explaining how to break a normal Dash app into separate files. It is particularly difficult to split out the `callbacks` into their own file without getting errors.

**Comment by ned2** [comment]
There's nothing special about the slapdash package other than it's arranged in a sensible way for a Dash project and that it happens to be a Python package. I find it easier to manage projects as Python packages.It gives you convenient way to install it into a virtualenv, and then you don't need to worry about your location when running the app. To install and run it's as simple as:

    $ pip install -e . gunicorn
    $ gunicorn slapdash.wsgi

If you don't want to install the package you can run it relative to the repository root like so:

    $ gunicorn src.slapdash.wsgi

But you will need to make sure you've installed all the dependencies found in `setup.py` into your virtualenv first. Which makes installing the package easier I reckon.

**Comment by brylie** [comment]
OK, thanks. For some reason, which you may have addressed in a different issue, I cannot figure out how to separate the callbacks, layouts, and app into separate files. I get import errors when trying relative imports, and the closes I have come without import errors doesn't seem to bind callbacks to the layout... frustrating.

**Comment by ned2** [comment]
I think you're problem is to do with circular imports and not actually to do specifically with relative imports, as I describe in #6.
