### ISSUE TITLE
Consider including dash-bootstrap-components

### ISSUE THREAD

**Issue by mungojam** [ned2/slapdash#8]
Rather than just providing Row and Column, by including [dash-bootstrap-components](https://github.com/ASIDataScience/dash-bootstrap-components), you could provide a default sidebar layout or something like that.

People starting out with Shiny tend to get shown nice bootstrap layouts in the getting-started guides, so it has more of a wow factor for beginners.

**Comment by ned2** [comment]
Oh that's super cool! I did not know about that project. That would make a lot of sense. I'll absolutely consider this :)

**Comment by dustyny** [comment]
I would like to also suggest this as well. I think you're filling an important need for Dash and dash-bootstrap-components looks like it has some velocity. 

I would really appreciate it if slapdash focused on a great boilerplate and integrations. If you can tie together a few solid Dash projects like dash-bootstrap, it could seriously improve the learning curve and save a bunch of time building a new project.

**Comment by ned2** [comment]
Dash Bootstrap Components are great! I've just merged #11, which was a fairly chunky PR, that amongst other improvements, switched most of Slapdash's layouts to use `dbs` components!

**Comment by pbugnion** [comment]
Hey! I'm one of the authors of dash-bootstrap-components. We just wanted to say thanks for including it in the boilerplate. We definitely value feedback, so if you have suggestions, just raise issues on the [repo](https://github.com/asidatascience/dash-bootstrap-components)!
